# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EW_EUAMXrrMMXA15pxmXY8Qxpym6s9i
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

data = {
    'Name':['Alice', 'Bob', 'Charlie', 'Daniela'],
    'Marks': [80, 90, 70, 85],
    'Age': [20, 21, 20, 19]
}
df = pd.DataFrame(data)

sns.lineplot(x='Name', y='Marks', data=df)
plt.title("Marks Line Chart")
plt.show()

sns.barplot(x='Name', y='Marks', data=df)
plt.title("Marks Bar Chart")
plt.show()

sns.scatterplot(x='Age', y='Marks', data=df)
plt.title("Age vs Marks ")
plt.show()

sns.histplot(df['Marks'], kde=True)
plt.title("Marks Distribution")
plt.show()

sns.boxplot(y='Marks', data=df)
plt.title("Marks box plot")
plt.show()